using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using POS.BLL;
using POS.Core;
using pos.UI;
using pos.UI.Busy;

namespace pos
{
    public partial class frm_supplier_payment : Form
    {
        private const string PaymentReferencePrefix = "[Payment Ref: ";

        private frm_addSupplier mainForm;
        private string _autoGeneratedDescription = string.Empty;
        public int _supplier_id;
        public string _supplier_name;
        public string _invoice_no;

        public int cash_account_id = 0;
        public int payable_account_id = 0;
        public int tax_account_id = 0;
        public int purchases_discount_acc_id = 0;
        public int inventory_acc_id = 0;
        public int purchases_acc_id = 0;

        public frm_supplier_payment(frm_addSupplier mainForm, int supplier_id, string supplier_name = "")
        {
            this.mainForm = mainForm;
            _supplier_id = supplier_id;
            _supplier_name = supplier_name;

            InitializeComponent();
            cmb_pendingInvoices.SelectedIndexChanged += cmb_pendingInvoices_SelectedIndexChanged;
            cmb_ref_account_code.SelectedIndexChanged += cmb_ref_account_code_SelectedIndexChanged;
        }

        public frm_supplier_payment()
        {
            InitializeComponent();
            cmb_pendingInvoices.SelectedIndexChanged += cmb_pendingInvoices_SelectedIndexChanged;
            cmb_ref_account_code.SelectedIndexChanged += cmb_ref_account_code_SelectedIndexChanged;
        }

        public void frm_supplier_payment_Load(object sender, EventArgs e)
        {
            using (BusyScope.Show(this, UiMessages.T("Loading...", "جاري التحميل...")))
            {
                Get_AccountID_From_Company();
                GetMAXInvoiceNo();
                get_accounts_dropdownlist();
                lblSupplierName.Text = _supplier_name;
                LoadPendingInvoices();
                UpdateSuggestedDescription();
            }
        }

        public void get_accounts_dropdownlist()
        {
            GeneralBLL generalBLL_obj = new GeneralBLL();
            string keyword = "id,name";
            string table = "acc_accounts where id IN (3,19)";

            DataTable accounts = generalBLL_obj.GetRecord(keyword, table);
            DataRow emptyRow = accounts.NewRow();
            emptyRow[0] = 0;
            emptyRow[1] = "Please Select";
            accounts.Rows.InsertAt(emptyRow, 0);

            cmb_GL_account_code.DisplayMember = "name";
            cmb_GL_account_code.ValueMember = "id";
            cmb_GL_account_code.DataSource = accounts;

            cmb_GL_account_code.SelectedValue = "3";
        }

        public void GetMAXInvoiceNo()
        {
            JournalsBLL JournalsBLL_obj = new JournalsBLL();
            _invoice_no = JournalsBLL_obj.GetMaxInvoiceNo();
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(_invoice_no) || _supplier_id == 0)
                {
                    UiMessages.ShowInfo("Please enter supplier payment details.", "يرجى إدخال بيانات دفعة المورد.", "Validation", "التحقق");
                    return;
                }

                double amount;
                if (!double.TryParse(txt_total_amount.Text, out amount) || amount <= 0)
                {
                    UiMessages.ShowInfo("Please enter a valid payment amount.", "يرجى إدخال مبلغ دفعة صحيح.", "Validation", "التحقق");
                    return;
                }

                double discountAmount = 0;
                if (!string.IsNullOrWhiteSpace(txt_discount.Text) && !double.TryParse(txt_discount.Text, out discountAmount))
                {
                    UiMessages.ShowInfo("Please enter a valid discount amount.", "يرجى إدخال مبلغ خصم صحيح.", "Validation", "التحقق");
                    return;
                }

                string appliedInvoiceNo = GetAppliedInvoiceNo();
                double appliedInvoiceBalance = GetAppliedInvoiceBalance();
                if (!string.IsNullOrWhiteSpace(appliedInvoiceNo) && (amount + discountAmount) > appliedInvoiceBalance + 0.0001)
                {
                    UiMessages.ShowWarning("Payment plus discount cannot be greater than the selected invoice balance.", "لا يمكن أن يكون مبلغ الدفعة مع الخصم أكبر من رصيد الفاتورة المحددة.", "Validation", "التحقق");
                    return;
                }

                var confirm = UiMessages.ConfirmYesNo("Post this supplier payment?", "هل تريد ترحيل دفعة المورد؟", captionEn: "Confirm", captionAr: "تأكيد");
                if (confirm != DialogResult.Yes)
                    return;

                using (BusyScope.Show(this, UiMessages.T("Posting payment...", "جاري ترحيل الدفعة...")))
                {
                    int glAccountId = (cmb_GL_account_code.SelectedValue == null ? 0 : int.Parse(cmb_GL_account_code.SelectedValue.ToString()));
                    int refAccountId = (cmb_ref_account_code.SelectedValue == null ? 0 : int.Parse(cmb_ref_account_code.SelectedValue.ToString()));

                    bool isBankPayment = new BankBLL().IsBankGlAccount(glAccountId);
                    string bankName = isBankPayment ? GetSelectedReferenceDisplayText() : string.Empty;
                    string userRemarks = GetEffectiveRemarks();

                    string ledgerInvoiceNo = string.IsNullOrWhiteSpace(appliedInvoiceNo) ? _invoice_no : appliedInvoiceNo;
                    string journalDescription = BuildPaymentDescription(appliedInvoiceNo, userRemarks, isBankPayment, bankName, false, _invoice_no, false);
                    string ledgerDescription = BuildPaymentDescription(appliedInvoiceNo, userRemarks, isBankPayment, bankName, true, _invoice_no, false);
                    string discountJournalDescription = BuildPaymentDescription(appliedInvoiceNo, userRemarks, isBankPayment, bankName, false, _invoice_no, true);
                    string discountLedgerDescription = BuildPaymentDescription(appliedInvoiceNo, userRemarks, isBankPayment, bankName, true, _invoice_no, true);

                    int entry_id = Insert_Journal_entry(_invoice_no, payable_account_id, amount, 0, txt_payment_date.Value.Date, journalDescription, 0, 0, 0, 0);
                    Insert_Journal_entry(_invoice_no, glAccountId, 0, amount, txt_payment_date.Value.Date, journalDescription, 0, 0, 0, 0);

                    if (refAccountId != 0 && isBankPayment)
                    {
                        Insert_Journal_entry(_invoice_no, glAccountId, 0, amount, txt_payment_date.Value.Date, journalDescription, 0, 0, entry_id, refAccountId);
                    }

                    Insert_Journal_entry(ledgerInvoiceNo, glAccountId, amount, 0, txt_payment_date.Value.Date, ledgerDescription, 0, _supplier_id, entry_id, 0);

                    if (!string.IsNullOrWhiteSpace(txt_discount.Text))
                    {
                        double discount;
                        if (double.TryParse(txt_discount.Text, out discount) && discount > 0)
                        {
                            Insert_Journal_entry(_invoice_no, payable_account_id, discount, 0, txt_payment_date.Value.Date, discountJournalDescription, 0, 0, 0, 0);
                            int entry_idd = Insert_Journal_entry(_invoice_no, purchases_discount_acc_id, 0, discount, txt_payment_date.Value.Date, discountJournalDescription, 0, 0, 0, 0);
                            Insert_Journal_entry(ledgerInvoiceNo, purchases_discount_acc_id, discount, 0, txt_payment_date.Value.Date, discountLedgerDescription, 0, _supplier_id, entry_idd, 0);
                        }
                    }

                    UiMessages.ShowInfo(
                        string.IsNullOrWhiteSpace(appliedInvoiceNo) ? "Supplier payment has been posted successfully." : "Supplier payment has been posted successfully against invoice " + appliedInvoiceNo + ".",
                        string.IsNullOrWhiteSpace(appliedInvoiceNo) ? "تم ترحيل دفعة المورد بنجاح." : "تم ترحيل دفعة المورد بنجاح مقابل الفاتورة " + appliedInvoiceNo + ".",
                        "Success",
                        "نجاح");

                    if (mainForm != null)
                        mainForm.load_transactions_grid(_supplier_id);

                    this.Close();
                }
            }
            catch (Exception ex)
            {
                UiMessages.ShowError(ex.Message, ex.Message);
            }
        }

        private int Insert_Journal_entry(string invoice_no, int account_id, double debit, double credit, DateTime date,
           string description, int customer_id, int supplier_id, int entry_id, int bank_id)
        {
            int journal_id = 0;
            JournalsModal JournalsModal_obj = new JournalsModal();
            JournalsBLL JournalsObj = new JournalsBLL();

            JournalsModal_obj.invoice_no = invoice_no;
            JournalsModal_obj.entry_date = date;
            JournalsModal_obj.debit = debit;
            JournalsModal_obj.credit = credit;
            JournalsModal_obj.account_id = account_id;
            JournalsModal_obj.description = description;
            JournalsModal_obj.customer_id = customer_id;
            JournalsModal_obj.supplier_id = supplier_id;
            JournalsModal_obj.entry_id = entry_id;
            JournalsModal_obj.bank_id = bank_id;

            journal_id = JournalsObj.Insert(JournalsModal_obj);
            return journal_id;
        }

        private void Get_AccountID_From_Company()
        {
            GeneralBLL objBLL = new GeneralBLL();
            DataTable companies_dt = objBLL.GetRecord("TOP 1 *", "pos_companies");
            foreach (DataRow dr in companies_dt.Rows)
            {
                cash_account_id = (int)dr["cash_acc_id"];
                payable_account_id = (int)dr["payable_acc_id"];
                tax_account_id = (int)dr["tax_acc_id"];
                purchases_discount_acc_id = (int)dr["purchases_discount_acc_id"];
                inventory_acc_id = (int)dr["inventory_acc_id"];
                purchases_acc_id = (int)dr["purchases_acc_id"];
            }
        }

        private void btn_cancel_Click(object sender, EventArgs e)
        {
            this.Dispose();
            this.Close();
        }

        private void frm_supplier_payment_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyData == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }

        private void txt_total_amount_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!char.IsControl(e.KeyChar) && !char.IsDigit(e.KeyChar) && (e.KeyChar != '.'))
            {
                e.Handled = true;
            }

            if ((e.KeyChar == '.') && ((sender as TextBox).Text.IndexOf('.') > -1))
            {
                e.Handled = true;
            }
        }

        private void txt_discount_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!char.IsControl(e.KeyChar) && !char.IsDigit(e.KeyChar) && (e.KeyChar != '.'))
            {
                e.Handled = true;
            }

            if ((e.KeyChar == '.') && ((sender as TextBox).Text.IndexOf('.') > -1))
            {
                e.Handled = true;
            }
        }

        private void BindCombo(ComboBox combo, DataTable dt, string valueMember, string displayMember, string type = "Account")
        {
            if (combo == null) return;

            combo.DataSource = null;
            combo.DisplayMember = displayMember;
            combo.ValueMember = valueMember;
            combo.DataSource = dt;

            combo.Enabled = (dt != null && dt.Rows.Count > 0);
            if (combo.Enabled)
                combo.SelectedIndex = 0;
        }

        private void ClearRefCombo()
        {
            if (cmb_ref_account_code == null) return;
            cmb_ref_account_code.DataSource = null;
            cmb_ref_account_code.Items.Clear();
            cmb_ref_account_code.Text = string.Empty;
            cmb_ref_account_code.Enabled = false;
        }

        private void cmb_GL_account_code_SelectedIndexChanged(object sender, EventArgs e)
        {
            int glAccountId = 0;
            try
            {
                glAccountId = (cmb_GL_account_code.SelectedValue == null)
                    ? 0
                    : Convert.ToInt32(cmb_GL_account_code.SelectedValue);
            }
            catch
            {
                glAccountId = 0;
            }

            if (glAccountId <= 0)
            {
                ClearRefCombo();
                UpdateSuggestedDescription();
                return;
            }

            BankBLL bankBLL = new BankBLL();
            if (bankBLL.IsBankGlAccount(glAccountId))
            {
                LoadBankAccountsIntoRefCombo(glAccountId);
                UpdateSuggestedDescription();
                return;
            }

            ClearRefCombo();
            UpdateSuggestedDescription();
        }

        private void LoadBankAccountsIntoRefCombo(int glAccountId)
        {
            try
            {
                GeneralBLL bll = new GeneralBLL();

                DataTable dt;
                try
                {
                    dt = bll.GetRecord("TOP 500 id, name, GLAccountID", "pos_banks");
                    DataView dv = dt.DefaultView;
                    dv.RowFilter = "GLAccountID = " + glAccountId;
                    BindCombo(cmb_ref_account_code, dv.ToTable(), "id", "name");
                    return;
                }
                catch
                {
                }

                dt = bll.GetRecord("TOP 500 id, name, GLAccountID", "pos_banks");
                DataView dv2 = dt.DefaultView;
                dv2.RowFilter = "GLAccountID = " + glAccountId;
                BindCombo(cmb_ref_account_code, dv2.ToTable(), "id", "name", "Bank");
            }
            catch
            {
                ClearRefCombo();
            }
        }

        private void LoadPendingInvoices()
        {
            if (cmb_pendingInvoices == null)
                return;

            cmb_pendingInvoices.DataSource = null;
            cmb_pendingInvoices.Items.Clear();

            if (_supplier_id <= 0)
            {
                cmb_pendingInvoices.Enabled = false;
                return;
            }

            SupplierBLL supplierBLL = new SupplierBLL();
            DataTable dt = supplierBLL.GetPendingSupplierInvoices(_supplier_id);

            if (!dt.Columns.Contains("invoice_no"))
                dt.Columns.Add("invoice_no", typeof(string));
            if (!dt.Columns.Contains("display_text"))
                dt.Columns.Add("display_text", typeof(string));
            if (!dt.Columns.Contains("balance_amount"))
                dt.Columns.Add("balance_amount", typeof(decimal));

            DataRow emptyRow = dt.NewRow();
            emptyRow["invoice_no"] = string.Empty;
            emptyRow["display_text"] = "-- Select Invoice --";
            emptyRow["balance_amount"] = 0m;
            dt.Rows.InsertAt(emptyRow, 0);

            cmb_pendingInvoices.DisplayMember = "display_text";
            cmb_pendingInvoices.ValueMember = "invoice_no";
            cmb_pendingInvoices.DataSource = dt;
            cmb_pendingInvoices.SelectedIndex = 0;
            cmb_pendingInvoices.Enabled = dt.Rows.Count > 1;
        }

        private void cmb_pendingInvoices_SelectedIndexChanged(object sender, EventArgs e)
        {
            string appliedInvoiceNo = GetAppliedInvoiceNo();
            double balance = GetAppliedInvoiceBalance();

            if (!string.IsNullOrWhiteSpace(appliedInvoiceNo))
            {
                double existingAmount;
                if (string.IsNullOrWhiteSpace(txt_total_amount.Text) || !double.TryParse(txt_total_amount.Text, out existingAmount) || existingAmount <= 0)
                    txt_total_amount.Text = Math.Round(balance, 2).ToString("N2");
            }

            UpdateSuggestedDescription();
        }

        private void cmb_ref_account_code_SelectedIndexChanged(object sender, EventArgs e)
        {
            UpdateSuggestedDescription();
        }

        private string GetAppliedInvoiceNo()
        {
            return cmb_pendingInvoices == null || cmb_pendingInvoices.SelectedValue == null
                ? string.Empty
                : Convert.ToString(cmb_pendingInvoices.SelectedValue);
        }

        private double GetAppliedInvoiceBalance()
        {
            if (cmb_pendingInvoices == null || cmb_pendingInvoices.SelectedItem == null)
                return 0;

            DataRowView rowView = cmb_pendingInvoices.SelectedItem as DataRowView;
            if (rowView == null || rowView.Row == null || !rowView.Row.Table.Columns.Contains("balance_amount"))
                return 0;

            double balance;
            return double.TryParse(Convert.ToString(rowView["balance_amount"]), out balance) ? balance : 0;
        }

        private void UpdateSuggestedDescription()
        {
            if (txt_description == null)
                return;

            string suggested = BuildPaymentDescription(
                GetAppliedInvoiceNo(),
                string.Empty,
                IsSelectedBankPayment(),
                GetSelectedReferenceDisplayText(),
                false,
                _invoice_no,
                false);

            string currentText = (txt_description.Text ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(currentText) || string.Equals(currentText, _autoGeneratedDescription, StringComparison.OrdinalIgnoreCase))
                txt_description.Text = suggested;

            _autoGeneratedDescription = suggested;
        }

        private string GetSelectedReferenceDisplayText()
        {
            if (cmb_ref_account_code == null)
                return string.Empty;

            DataRowView rowView = cmb_ref_account_code.SelectedItem as DataRowView;
            if (rowView != null)
            {
                if (rowView.Row.Table.Columns.Contains("display_name"))
                    return Convert.ToString(rowView["display_name"]);

                if (rowView.Row.Table.Columns.Contains("name"))
                    return Convert.ToString(rowView["name"]);
            }

            return Convert.ToString(cmb_ref_account_code.Text);
        }

        private string GetSelectedGlAccountDisplayText()
        {
            return cmb_GL_account_code == null ? string.Empty : Convert.ToString(cmb_GL_account_code.Text);
        }

        private bool IsSelectedBankPayment()
        {
            int glAccountId;
            if (cmb_GL_account_code == null || cmb_GL_account_code.SelectedValue == null || !int.TryParse(Convert.ToString(cmb_GL_account_code.SelectedValue), out glAccountId))
                return false;

            return new BankBLL().IsBankGlAccount(glAccountId);
        }

        private string GetEffectiveRemarks()
        {
            string currentText = (txt_description.Text ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(currentText))
                return string.Empty;

            return string.Equals(currentText, _autoGeneratedDescription, StringComparison.OrdinalIgnoreCase)
                ? string.Empty
                : currentText;
        }

        private string BuildPaymentDescription(string appliedInvoiceNo, string remarks, bool isBankPayment, string bankName, bool includePaymentReference, string paymentReferenceInvoiceNo, bool isDiscount)
        {
            bool isArabic = IsArabicEnvironment();

            string invoicePart = string.IsNullOrWhiteSpace(appliedInvoiceNo)
                ? (isArabic ? "على حساب المورد" : "on supplier account")
                : (isArabic ? "مقابل الفاتورة " + appliedInvoiceNo : "against invoice " + appliedInvoiceNo);

            string paymentMode = isBankPayment
                ? (string.IsNullOrWhiteSpace(bankName)
                    ? (isArabic ? "البنك" : "Bank")
                    : (isArabic ? "البنك: " + bankName : "Bank: " + bankName))
                : GetSelectedGlAccountDisplayText();

            if (string.IsNullOrWhiteSpace(paymentMode))
                paymentMode = isBankPayment
                    ? (isArabic ? "البنك" : "Bank")
                    : (isArabic ? "النقد" : "Cash");

            string description = isDiscount
                ? (isArabic
                    ? "تم ترحيل خصم دفعة المورد " + invoicePart + " عبر " + paymentMode + "."
                    : "Supplier payment discount posted " + invoicePart + " via " + paymentMode + ".")
                : (isArabic
                    ? "تم دفع مبلغ للمورد " + invoicePart + " عبر " + paymentMode + "."
                    : "Supplier payment posted " + invoicePart + " via " + paymentMode + ".");

            if (!string.IsNullOrWhiteSpace(remarks))
                description += isArabic
                    ? " ملاحظات: " + remarks.Trim() + "."
                    : " Remarks: " + remarks.Trim() + ".";

            if (includePaymentReference && !string.IsNullOrWhiteSpace(paymentReferenceInvoiceNo))
                description += " " + PaymentReferencePrefix + paymentReferenceInvoiceNo + "]";

            return description.Trim();
        }

        private static bool IsArabicEnvironment()
        {
            string lang = UsersModal.logged_in_lang ?? string.Empty;
            return lang.StartsWith("ar", StringComparison.OrdinalIgnoreCase);
        }
    }
}
