using POS.BLL;
using POS.Core;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Printing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;
using pos.Accounts.Reports;
using pos.UI;
using pos.UI.Busy;

namespace pos.Reports.Financial
{
    public partial class frm_ProfitAndLossReport : Form
    {
        private readonly AccountsBLL _accountsBll = new AccountsBLL();
        private readonly List<ReportLine> _reportLines = new List<ReportLine>();

        private DateTime _activeFrom;
        private DateTime _activeTo;
        private DateTime? _previousFrom;
        private DateTime? _previousTo;
        private decimal _totalIncome;
        private bool _isInitializing;

        public frm_ProfitAndLossReport()
        {
            InitializeComponent();
            WireEvents();
        }

        private void WireEvents()
        {
            Load += Frm_ProfitAndLossReport_Load;
            cmbPeriod.SelectedIndexChanged += CmbPeriod_SelectedIndexChanged;
            btnGenerate.Click += BtnGenerate_Click;
            btnPrintPreview.Click += BtnPrintPreview_Click;
            btnExportExcel.Click += BtnExportExcel_Click;
            btnExportPdf.Click += BtnExportPdf_Click;
            btnEmail.Click += BtnEmail_Click;
            chkShowComparison.CheckedChanged += ChkShowComparison_CheckedChanged;
            chkShowPercentage.CheckedChanged += (s, e) => ApplyColumnVisibility();
            cmbDetailLevel.SelectedIndexChanged += (s, e) => GenerateReport();
            cmbCostCenter.SelectedIndexChanged += (s, e) => { if (IsHandleCreated) GenerateReport(); };
            treeReport.DrawNode += TreeReport_DrawNode;
            treeReport.NodeMouseDoubleClick += TreeReport_NodeMouseDoubleClick;
            treeReport.NodeMouseHover += TreeReport_NodeMouseHover;
            treeReport.MouseLeave += (s, e) => treeReport.Cursor = Cursors.Default;
            dtpFrom.ValueChanged += (s, e) => { if (!_isInitializing && string.Equals(Convert.ToString(cmbPeriod.SelectedItem), "Custom Range", StringComparison.OrdinalIgnoreCase)) GenerateReport(); };
            dtpTo.ValueChanged += (s, e) => { if (!_isInitializing && string.Equals(Convert.ToString(cmbPeriod.SelectedItem), "Custom Range", StringComparison.OrdinalIgnoreCase)) GenerateReport(); };
        }

        private void Frm_ProfitAndLossReport_Load(object sender, EventArgs e)
        {
            AppTheme.Apply(this);
            Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);

            _isInitializing = true;

            lblCompanyName.Text = string.IsNullOrWhiteSpace(UsersModal.logged_in_company_name)
                ? "Company"
                : UsersModal.logged_in_company_name;
            lblGeneratedBy.Text = "Generated By: " + (string.IsNullOrWhiteSpace(UsersModal.logged_in_username) ? "-" : UsersModal.logged_in_username);

            cmbPeriod.Items.AddRange(new object[] { "This Month", "This Quarter", "This Year", "Custom Range" });
            cmbDetailLevel.Items.AddRange(new object[] { "Summarized (Level 1+2)", "Detailed (show all Level 3 accounts)" });

            cmbPeriod.SelectedIndex = 0;
            cmbDetailLevel.SelectedIndex = 1;
            chkShowComparison.Checked = false;
            chkShowPercentage.Checked = true;

            LoadCostCenters();
            ApplyColumnVisibility();
            ApplyPeriodPreset();

            _isInitializing = false;
            GenerateReport();
        }

        private void CmbPeriod_SelectedIndexChanged(object sender, EventArgs e)
        {
            ApplyPeriodPreset();

            if (!_isInitializing)
            {
                GenerateReport();
            }
        }

        private void ApplyPeriodPreset()
        {
            DateTime today = DateTime.Today;
            DateTime from;
            DateTime to;

            switch (Convert.ToString(cmbPeriod.SelectedItem))
            {
                case "This Quarter":
                    int quarterStartMonth = ((today.Month - 1) / 3) * 3 + 1;
                    from = new DateTime(today.Year, quarterStartMonth, 1);
                    to = from.AddMonths(3).AddDays(-1);
                    break;

                case "This Year":
                    from = new DateTime(today.Year, 1, 1);
                    to = new DateTime(today.Year, 12, 31);
                    break;

                case "Custom Range":
                    dtpFrom.Enabled = true;
                    dtpTo.Enabled = true;
                    return;

                default:
                    from = new DateTime(today.Year, today.Month, 1);
                    to = from.AddMonths(1).AddDays(-1);
                    break;
            }

            dtpFrom.Enabled = false;
            dtpTo.Enabled = false;
            dtpFrom.Value = from;
            dtpTo.Value = to;
        }

        private void LoadCostCenters()
        {
            DataTable dt = _accountsBll.GetProfitLossCostCenters();
            DataTable source = new DataTable();
            source.Columns.Add("id", typeof(int));
            source.Columns.Add("name", typeof(string));
            source.Rows.Add(DBNull.Value, "All Departments");

            foreach (DataRow row in dt.Rows)
            {
                source.Rows.Add(row["id"] == DBNull.Value ? (object)DBNull.Value : row["id"], Convert.ToString(row["name"]));
            }

            cmbCostCenter.DisplayMember = "name";
            cmbCostCenter.ValueMember = "id";
            cmbCostCenter.DataSource = source;
            cmbCostCenter.SelectedIndex = 0;
        }

        private void BtnGenerate_Click(object sender, EventArgs e)
        {
            GenerateReport();
        }

        private void ChkShowComparison_CheckedChanged(object sender, EventArgs e)
        {
            ApplyColumnVisibility();
            GenerateReport();
        }

        private void GenerateReport()
        {
            if (dtpFrom.Value.Date > dtpTo.Value.Date)
            {
                UiMessages.ShowError("From date cannot be after To date.", "لا يمكن أن يكون تاريخ البداية بعد تاريخ النهاية.");
                return;
            }

            try
            {
                using (BusyScope.Show(this, UiMessages.T("Generating income statement...", "جاري إنشاء قائمة الدخل...")))
                {
                    _activeFrom = dtpFrom.Value.Date;
                    _activeTo = dtpTo.Value.Date;

                    if (chkShowComparison.Checked)
                    {
                        Tuple<DateTime, DateTime> previous = ResolvePreviousPeriod(_activeFrom, _activeTo);
                        _previousFrom = previous.Item1;
                        _previousTo = previous.Item2;
                    }
                    else
                    {
                        _previousFrom = null;
                        _previousTo = null;
                    }

                    DataTable hierarchyTable = _accountsBll.GetProfitLossHierarchy();
                    int? costCenterId = cmbCostCenter.SelectedValue == null || cmbCostCenter.SelectedValue == DBNull.Value
                        ? (int?)null
                        : Convert.ToInt32(cmbCostCenter.SelectedValue);

                    DataTable balancesTable = _accountsBll.GetProfitLossBalances(_activeFrom, _activeTo, _previousFrom, _previousTo, costCenterId);

                    BuildReportTree(hierarchyTable, balancesTable, IsDetailedView());
                    BindTree();
                    UpdateHeader();
                }
            }
            catch (Exception ex)
            {
                UiMessages.ShowError(ex.Message, ex.Message);
            }
        }

        private static Tuple<DateTime, DateTime> ResolvePreviousPeriod(DateTime from, DateTime to)
        {
            int days = (to - from).Days + 1;
            DateTime previousTo = from.AddDays(-1);
            DateTime previousFrom = previousTo.AddDays(-(days - 1));
            return Tuple.Create(previousFrom, previousTo);
        }

        private bool IsDetailedView()
        {
            string text = Convert.ToString(cmbDetailLevel.SelectedItem);
            return !string.IsNullOrWhiteSpace(text) && text.StartsWith("Detailed", StringComparison.OrdinalIgnoreCase);
        }

        private void BuildReportTree(DataTable hierarchyTable, DataTable balancesTable, bool detailed)
        {
            _reportLines.Clear();

            Dictionary<int, BalanceInfo> balances = ParseBalances(balancesTable);
            Dictionary<int, GroupInfo> groups;
            List<AccountInfo> accounts;
            ParseHierarchy(hierarchyTable, balances, out groups, out accounts);

            List<ReportLine> incomeLines = BuildSectionLines("Income", groups, accounts, detailed);
            List<ReportLine> cogsLines = BuildSectionLines("COGS", groups, accounts, detailed);
            List<ReportLine> expenseLines = BuildSectionLines("Expense", groups, accounts, detailed);
            List<ReportLine> otherLines = BuildSectionLines("Other", groups, accounts, detailed);

            decimal totalIncome = incomeLines.Sum(x => x.CurrentAmount);
            decimal totalCogs = cogsLines.Sum(x => x.CurrentAmount);
            decimal grossProfit = totalIncome - totalCogs;
            decimal grossMarginPercent = totalIncome == 0m ? 0m : (grossProfit / totalIncome) * 100m;
            decimal totalExpense = expenseLines.Sum(x => x.CurrentAmount);
            decimal operatingProfit = grossProfit - totalExpense;
            decimal otherResult = otherLines.Sum(x => x.CurrentAmount);
            decimal netProfit = operatingProfit + otherResult;

            _totalIncome = totalIncome;

            _reportLines.Add(ReportLine.SectionHeader("INCOME SECTION"));
            _reportLines.AddRange(incomeLines);
            _reportLines.Add(ReportLine.Subtotal("Total Income", totalIncome));

            _reportLines.Add(ReportLine.SectionHeader("COST OF GOODS SOLD"));
            _reportLines.AddRange(cogsLines);
            _reportLines.Add(ReportLine.Highlight("Gross Profit", grossProfit));
            _reportLines.Add(ReportLine.MutedMetric("Gross Profit Margin %", grossMarginPercent));

            _reportLines.Add(ReportLine.SectionHeader("OPERATING EXPENSES"));
            _reportLines.AddRange(expenseLines);
            _reportLines.Add(ReportLine.Subtotal("Total Operating Expenses", totalExpense));
            _reportLines.Add(ReportLine.Highlight("Operating Profit / (Loss)", operatingProfit));

            if (otherLines.Count > 0)
            {
                _reportLines.Add(ReportLine.SectionHeader("OTHER INCOME / EXPENSES"));
                _reportLines.AddRange(otherLines);
            }

            _reportLines.Add(ReportLine.NetResult("Net Profit / (Loss)", netProfit));

            foreach (ReportLine line in _reportLines)
            {
                ComputePercentRecursive(line, totalIncome);
            }
        }

        private static Dictionary<int, BalanceInfo> ParseBalances(DataTable balancesTable)
        {
            var map = new Dictionary<int, BalanceInfo>();
            foreach (DataRow row in balancesTable.Rows)
            {
                int accountId = row["account_id"] == DBNull.Value ? 0 : Convert.ToInt32(row["account_id"]);
                if (accountId <= 0)
                {
                    continue;
                }

                map[accountId] = new BalanceInfo
                {
                    CurrentDebit = row["current_debit"] == DBNull.Value ? 0m : Convert.ToDecimal(row["current_debit"]),
                    CurrentCredit = row["current_credit"] == DBNull.Value ? 0m : Convert.ToDecimal(row["current_credit"]),
                    PreviousDebit = row["previous_debit"] == DBNull.Value ? 0m : Convert.ToDecimal(row["previous_debit"]),
                    PreviousCredit = row["previous_credit"] == DBNull.Value ? 0m : Convert.ToDecimal(row["previous_credit"])
                };
            }

            return map;
        }

        private static void ParseHierarchy(DataTable hierarchyTable, Dictionary<int, BalanceInfo> balances, out Dictionary<int, GroupInfo> groups, out List<AccountInfo> accounts)
        {
            groups = new Dictionary<int, GroupInfo>();
            accounts = new List<AccountInfo>();

            foreach (DataRow row in hierarchyTable.Rows)
            {
                string kind = Convert.ToString(row["node_kind"]);
                if (string.Equals(kind, "Group", StringComparison.OrdinalIgnoreCase))
                {
                    int groupId = row["group_id"] == DBNull.Value ? 0 : Convert.ToInt32(row["group_id"]);
                    if (groupId <= 0)
                    {
                        continue;
                    }

                    groups[groupId] = new GroupInfo
                    {
                        Id = groupId,
                        ParentId = row["parent_id"] == DBNull.Value ? 0 : Convert.ToInt32(row["parent_id"]),
                        Code = Convert.ToString(row["code"]),
                        Name = Convert.ToString(row["name"]),
                        Section = Convert.ToString(row["section"])
                    };
                }
                else if (string.Equals(kind, "Account", StringComparison.OrdinalIgnoreCase))
                {
                    int accountId = row["account_id"] == DBNull.Value ? 0 : Convert.ToInt32(row["account_id"]);
                    if (accountId <= 0)
                    {
                        continue;
                    }

                    BalanceInfo balance;
                    if (!balances.TryGetValue(accountId, out balance))
                    {
                        balance = new BalanceInfo();
                    }

                    string section = Convert.ToString(row["section"]);
                    accounts.Add(new AccountInfo
                    {
                        Id = accountId,
                        GroupId = row["group_id"] == DBNull.Value ? 0 : Convert.ToInt32(row["group_id"]),
                        Code = Convert.ToString(row["code"]),
                        Name = Convert.ToString(row["name"]),
                        Section = section,
                        CurrentAmount = ToProfitLossAmount(section, balance.CurrentDebit, balance.CurrentCredit),
                        PreviousAmount = ToProfitLossAmount(section, balance.PreviousDebit, balance.PreviousCredit)
                    });
                }
            }
        }

        private static decimal ToProfitLossAmount(string section, decimal debit, decimal credit)
        {
            if (string.Equals(section, "Income", StringComparison.OrdinalIgnoreCase))
            {
                return credit - debit;
            }

            return debit - credit;
        }

        private static List<ReportLine> BuildSectionLines(string section, Dictionary<int, GroupInfo> groups, List<AccountInfo> accounts, bool detailed)
        {
            var sectionGroups = groups.Values.Where(x => string.Equals(x.Section, section, StringComparison.OrdinalIgnoreCase)).ToDictionary(x => x.Id, x => x);
            var groupChildren = sectionGroups.Values.GroupBy(x => x.ParentId).ToDictionary(g => g.Key, g => g.OrderBy(x => x.Code).ThenBy(x => x.Name).ToList());
            var accountsByGroup = accounts.Where(x => string.Equals(x.Section, section, StringComparison.OrdinalIgnoreCase)).GroupBy(x => x.GroupId).ToDictionary(g => g.Key, g => g.OrderBy(x => x.Code).ThenBy(x => x.Name).ToList());

            var roots = sectionGroups.Values.Where(g => g.ParentId == 0 || !sectionGroups.ContainsKey(g.ParentId)).OrderBy(x => x.Code).ThenBy(x => x.Name).ToList();
            var lines = new List<ReportLine>();
            foreach (GroupInfo root in roots)
            {
                ReportLine line = BuildGroupLineRecursive(root, groupChildren, accountsByGroup, detailed, 1);
                if (line != null)
                {
                    lines.Add(line);
                }
            }

            return lines;
        }

        private static ReportLine BuildGroupLineRecursive(GroupInfo group, Dictionary<int, List<GroupInfo>> groupChildren, Dictionary<int, List<AccountInfo>> accountsByGroup, bool detailed, int level)
        {
            var line = new ReportLine
            {
                Name = string.IsNullOrWhiteSpace(group.Name) ? "(Group)" : group.Name,
                LineType = ReportLineType.Group,
                Level = level,
                Children = new List<ReportLine>()
            };

            List<GroupInfo> children;
            if (groupChildren.TryGetValue(group.Id, out children))
            {
                foreach (GroupInfo child in children)
                {
                    ReportLine childLine = BuildGroupLineRecursive(child, groupChildren, accountsByGroup, detailed, level + 1);
                    if (childLine != null)
                    {
                        line.CurrentAmount += childLine.CurrentAmount;
                        line.PreviousAmount += childLine.PreviousAmount;

                        if (detailed || level <= 1)
                        {
                            line.Children.Add(childLine);
                        }
                    }
                }
            }

            List<AccountInfo> accountList;
            if (accountsByGroup.TryGetValue(group.Id, out accountList))
            {
                foreach (AccountInfo account in accountList)
                {
                    line.CurrentAmount += account.CurrentAmount;
                    line.PreviousAmount += account.PreviousAmount;

                    if (detailed)
                    {
                        line.Children.Add(new ReportLine
                        {
                            Name = string.IsNullOrWhiteSpace(account.Code) ? account.Name : account.Code + " - " + account.Name,
                            LineType = ReportLineType.Account,
                            AccountId = account.Id,
                            Level = level + 1,
                            CurrentAmount = account.CurrentAmount,
                            PreviousAmount = account.PreviousAmount,
                            IsClickable = true
                        });
                    }
                }
            }

            if (line.Children.Count == 0 && line.CurrentAmount == 0m && line.PreviousAmount == 0m)
            {
                return null;
            }

            return line;
        }

        private static void ComputePercentRecursive(ReportLine line, decimal totalIncome)
        {
            if (Math.Abs(totalIncome) > 0.0001m)
            {
                line.PercentOfIncome = (line.CurrentAmount / totalIncome) * 100m;
            }

            if (line.Children == null)
            {
                return;
            }

            foreach (ReportLine child in line.Children)
            {
                ComputePercentRecursive(child, totalIncome);
            }
        }

        private void BindTree()
        {
            treeReport.BeginUpdate();
            try
            {
                treeReport.Nodes.Clear();

                foreach (ReportLine line in _reportLines)
                {
                    AddTreeNode(treeReport.Nodes, line);
                }

                treeReport.ExpandAll();
            }
            finally
            {
                treeReport.EndUpdate();
            }
        }

        private static void AddTreeNode(TreeNodeCollection nodes, ReportLine line)
        {
            var node = new TreeNode(line.Name) { Tag = line };
            nodes.Add(node);

            if (line.Children == null)
            {
                return;
            }

            foreach (ReportLine child in line.Children)
            {
                AddTreeNode(node.Nodes, child);
            }
        }

        private void UpdateHeader()
        {
            lblReportTitle.Text = "Income Statement (Profit & Loss)";
            lblReportPeriod.Text = string.Format("Period: {0:yyyy-MM-dd} to {1:yyyy-MM-dd}", _activeFrom, _activeTo);
            lblGeneratedOn.Text = "Generated Date: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm");
            lblGeneratedBy.Text = "Generated By: " + (string.IsNullOrWhiteSpace(UsersModal.logged_in_username) ? "-" : UsersModal.logged_in_username);

            if (_previousFrom.HasValue && _previousTo.HasValue)
            {
                lblColPrevious.Text = string.Format("Previous ({0:MM/dd}-{1:MM/dd})", _previousFrom.Value, _previousTo.Value);
            }
            else
            {
                lblColPrevious.Text = "Previous Period";
            }
        }

        private void ApplyColumnVisibility()
        {
            lblColPercent.Visible = chkShowPercentage.Checked;
            lblColPrevious.Visible = chkShowComparison.Checked;
            lblColVariance.Visible = chkShowComparison.Checked;
            treeReport.Invalidate();
        }

        private void TreeReport_NodeMouseDoubleClick(object sender, TreeNodeMouseClickEventArgs e)
        {
            ReportLine line = e.Node.Tag as ReportLine;
            if (line == null || !line.IsClickable || !line.AccountId.HasValue)
            {
                return;
            }

            var ledger = new FrmAccountDetail(line.AccountId.Value, _activeFrom, _activeTo);
            ledger.ShowDialog(this);
        }

        private void TreeReport_NodeMouseHover(object sender, TreeNodeMouseHoverEventArgs e)
        {
            ReportLine line = e.Node.Tag as ReportLine;
            treeReport.Cursor = (line != null && line.IsClickable) ? Cursors.Hand : Cursors.Default;
        }

        private void TreeReport_DrawNode(object sender, DrawTreeNodeEventArgs e)
        {
            e.DrawDefault = false;

            Graphics g = e.Graphics;
            ReportLine line = e.Node.Tag as ReportLine;
            if (line == null)
            {
                e.DrawDefault = true;
                return;
            }

            var state = g.Save();
            try
            {
                g.SetClip(new Rectangle(0, e.Bounds.Top, treeReport.ClientSize.Width, e.Bounds.Height));

                Color backColor = (e.State & TreeNodeStates.Selected) == TreeNodeStates.Selected ? Color.FromArgb(224, 236, 255) : treeReport.BackColor;
                using (var backBrush = new SolidBrush(backColor))
                {
                    g.FillRectangle(backBrush, new Rectangle(0, e.Bounds.Top, treeReport.ClientSize.Width, e.Bounds.Height));
                }

                Font font = treeReport.Font;
                Color foreColor = AppTheme.TextPrimary;

                if (line.LineType == ReportLineType.SectionHeader)
                {
                    font = new Font(treeReport.Font, FontStyle.Bold);
                    foreColor = Color.FromArgb(27, 94, 32);
                }
                else if (line.LineType == ReportLineType.Subtotal || line.LineType == ReportLineType.Highlight)
                {
                    font = new Font(treeReport.Font, FontStyle.Bold);
                    foreColor = Color.FromArgb(13, 71, 161);
                }
                else if (line.LineType == ReportLineType.NetResult)
                {
                    font = new Font(treeReport.Font.FontFamily, treeReport.Font.Size + 1.5f, FontStyle.Bold);
                    foreColor = line.CurrentAmount >= 0 ? Color.ForestGreen : Color.Firebrick;
                }
                else if (line.LineType == ReportLineType.MutedMetric)
                {
                    foreColor = Color.DimGray;
                }
                else if (line.IsClickable)
                {
                    font = new Font(treeReport.Font, FontStyle.Underline);
                    foreColor = Color.FromArgb(25, 118, 210);
                }

                int clientWidth = treeReport.ClientSize.Width;
                int amountX = clientWidth - 430;
                int percentX = clientWidth - 300;
                int previousX = clientWidth - 200;
                int varianceX = clientWidth - 95;
                int textTop = e.Bounds.Top + 2;
                int textHeight = e.Bounds.Height - 4;
                int nameWidth = Math.Max(120, amountX - e.Bounds.Left - 12);

                TextRenderer.DrawText(
                    g,
                    line.Name,
                    font,
                    new Rectangle(e.Bounds.Left, textTop, nameWidth, textHeight),
                    foreColor,
                    TextFormatFlags.Left | TextFormatFlags.VerticalCenter | TextFormatFlags.EndEllipsis | TextFormatFlags.NoPrefix);

                TextRenderer.DrawText(
                    g,
                    FormatAmount(line.CurrentAmount, line.LineType == ReportLineType.MutedMetric),
                    font,
                    new Rectangle(amountX, textTop, 100, textHeight),
                    foreColor,
                    TextFormatFlags.Right | TextFormatFlags.VerticalCenter | TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix);

                if (chkShowPercentage.Checked)
                {
                    TextRenderer.DrawText(
                        g,
                        line.PercentOfIncome.ToString("N2", CultureInfo.InvariantCulture) + "%",
                        treeReport.Font,
                        new Rectangle(percentX, textTop, 90, textHeight),
                        Color.DimGray,
                        TextFormatFlags.Right | TextFormatFlags.VerticalCenter | TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix);
                }

                if (chkShowComparison.Checked)
                {
                    TextRenderer.DrawText(
                        g,
                        line.PreviousAmount.ToString("N2", CultureInfo.InvariantCulture),
                        treeReport.Font,
                        new Rectangle(previousX, textTop, 90, textHeight),
                        Color.Gray,
                        TextFormatFlags.Right | TextFormatFlags.VerticalCenter | TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix);
                    string varianceText = BuildVarianceText(line.CurrentAmount, line.PreviousAmount);
                    Color varianceColor = line.CurrentAmount >= line.PreviousAmount ? Color.ForestGreen : Color.Firebrick;
                    TextRenderer.DrawText(
                        g,
                        varianceText,
                        treeReport.Font,
                        new Rectangle(varianceX, textTop, 90, textHeight),
                        varianceColor,
                        TextFormatFlags.Right | TextFormatFlags.VerticalCenter | TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix);
                }
            }
            finally
            {
                g.Restore(state);
            }
        }

        private static string FormatAmount(decimal amount, bool isPercentLine)
        {
            if (isPercentLine)
            {
                return amount.ToString("N2", CultureInfo.InvariantCulture) + "%";
            }

            return amount.ToString("N2", CultureInfo.InvariantCulture);
        }

        private static string BuildVarianceText(decimal current, decimal previous)
        {
            if (previous == 0m)
            {
                return current == 0m ? "→ 0.00%" : "▲ 100.00%";
            }

            decimal change = ((current - previous) / Math.Abs(previous)) * 100m;
            string arrow = change >= 0m ? "▲" : "▼";
            return string.Format(CultureInfo.InvariantCulture, "{0} {1:N2}%", arrow, Math.Abs(change));
        }

        private void BtnPrintPreview_Click(object sender, EventArgs e)
        {
            using (PrintPreviewDialog preview = new PrintPreviewDialog())
            {
                preview.Document = CreatePrintDocument();
                preview.WindowState = FormWindowState.Maximized;
                preview.ShowDialog(this);
            }
        }

        private void BtnExportExcel_Click(object sender, EventArgs e)
        {
            if (_reportLines.Count == 0)
            {
                UiMessages.ShowInfo("Generate the report first.", "قم بإنشاء التقرير أولاً.");
                return;
            }

            using (SaveFileDialog save = new SaveFileDialog())
            {
                save.Title = "Export Profit & Loss to Excel";
                save.Filter = "Excel CSV (*.csv)|*.csv";
                save.FileName = "ProfitLoss_" + DateTime.Now.ToString("yyyyMMdd_HHmm");
                if (save.ShowDialog(this) != DialogResult.OK)
                {
                    return;
                }

                List<ExportRow> rows = BuildExportRows();
                WriteCsvWithFormulas(save.FileName, rows);
                UiMessages.ShowInfo("Excel export completed.", "تم تصدير ملف إكسل بنجاح.");
            }
        }

        private void BtnExportPdf_Click(object sender, EventArgs e)
        {
            ExportPdfInteractive();
        }

        private void BtnEmail_Click(object sender, EventArgs e)
        {
            string tempPdfPath = Path.Combine(Path.GetTempPath(), "ProfitLoss_" + DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".pdf");
            if (!ExportPdfToPath(tempPdfPath, true))
            {
                return;
            }

            if (!OpenComposeWithAttachment(tempPdfPath))
            {
                UiMessages.ShowWarning("Unable to open email compose with attachment on this machine.", "تعذر فتح نافذة البريد بالمرفق على هذا الجهاز.");
                return;
            }

            UiMessages.ShowInfo("Email compose opened with PDF attachment.", "تم فتح نافذة البريد مع مرفق PDF.");
        }

        private void ExportPdfInteractive()
        {
            using (SaveFileDialog save = new SaveFileDialog())
            {
                save.Title = "Export Profit & Loss PDF";
                save.Filter = "PDF files (*.pdf)|*.pdf";
                save.FileName = "ProfitLoss_" + DateTime.Now.ToString("yyyyMMdd_HHmm");
                if (save.ShowDialog(this) != DialogResult.OK)
                {
                    return;
                }

                if (ExportPdfToPath(save.FileName, false))
                {
                    UiMessages.ShowInfo("PDF export completed.", "تم تصدير ملف PDF بنجاح.");
                }
            }
        }

        private bool ExportPdfToPath(string path, bool silent)
        {
            try
            {
                PrintDocument document = CreatePrintDocument();
                document.PrinterSettings.PrinterName = "Microsoft Print to PDF";

                if (!document.PrinterSettings.IsValid)
                {
                    if (!silent)
                    {
                        UiMessages.ShowWarning("Microsoft Print to PDF printer is not available.", "طابعة Microsoft Print to PDF غير متوفرة.");
                    }
                    return false;
                }

                document.PrinterSettings.PrintToFile = true;
                document.PrinterSettings.PrintFileName = path;
                document.DefaultPageSettings.Landscape = false;
                document.PrintController = new StandardPrintController();
                document.Print();
                return File.Exists(path);
            }
            catch (Exception ex)
            {
                if (!silent)
                {
                    UiMessages.ShowError(ex.Message, ex.Message);
                }
                return false;
            }
        }

        private PrintDocument CreatePrintDocument()
        {
            List<PrintRow> rows = BuildPrintRows();
            int currentIndex = 0;

            PrintDocument document = new PrintDocument();
            document.DocumentName = "Profit & Loss";
            document.DefaultPageSettings.PaperSize = new PaperSize("A4", 827, 1169);

            document.PrintPage += (s, e) =>
            {
                int left = e.MarginBounds.Left;
                int y = e.MarginBounds.Top;
                int width = e.MarginBounds.Width;

                using (Font titleFont = new Font("Segoe UI", 12F, FontStyle.Bold))
                using (Font headFont = new Font("Segoe UI", 8F, FontStyle.Bold))
                using (Font bodyFont = new Font("Segoe UI", 8F))
                using (Pen linePen = new Pen(Color.Silver))
                {
                    e.Graphics.DrawString(lblCompanyName.Text, titleFont, Brushes.Black, left, y);
                    y += 22;
                    e.Graphics.DrawString("Income Statement (Profit & Loss)", titleFont, Brushes.Black, left, y);
                    y += 20;
                    e.Graphics.DrawString(lblReportPeriod.Text, bodyFont, Brushes.DimGray, left, y);
                    y += 18;

                    int colName = left;
                    int colAmt = left + width - 260;
                    int colPct = left + width - 160;
                    int colPrev = left + width - 80;

                    e.Graphics.DrawString("Account", headFont, Brushes.Black, colName, y);
                    e.Graphics.DrawString("Amount", headFont, Brushes.Black, colAmt, y);
                    e.Graphics.DrawString("% Income", headFont, Brushes.Black, colPct, y);
                    if (chkShowComparison.Checked)
                    {
                        e.Graphics.DrawString("Prev", headFont, Brushes.Black, colPrev, y);
                    }

                    y += 16;
                    e.Graphics.DrawLine(linePen, left, y, left + width, y);
                    y += 4;

                    while (currentIndex < rows.Count)
                    {
                        if (y + 16 > e.MarginBounds.Bottom)
                        {
                            e.HasMorePages = true;
                            return;
                        }

                        PrintRow row = rows[currentIndex];
                        Font rowFont = row.Bold ? headFont : bodyFont;
                        Brush rowBrush = row.ForeColor.HasValue ? new SolidBrush(row.ForeColor.Value) : Brushes.Black;

                        e.Graphics.DrawString(row.Name, rowFont, rowBrush, colName + (row.Level * 14), y);
                        e.Graphics.DrawString(row.AmountText, rowFont, rowBrush, colAmt, y);
                        if (chkShowPercentage.Checked)
                        {
                            e.Graphics.DrawString(row.PercentText, bodyFont, Brushes.DimGray, colPct, y);
                        }
                        if (chkShowComparison.Checked)
                        {
                            e.Graphics.DrawString(row.PreviousText, bodyFont, Brushes.Gray, colPrev, y);
                        }

                        if (!ReferenceEquals(rowBrush, Brushes.Black))
                        {
                            rowBrush.Dispose();
                        }

                        y += 16;
                        currentIndex++;
                    }
                }

                e.HasMorePages = false;
            };

            return document;
        }

        private List<PrintRow> BuildPrintRows()
        {
            var rows = new List<PrintRow>();
            foreach (ReportLine line in _reportLines)
            {
                AddPrintRowsRecursive(rows, line, 0);
            }

            return rows;
        }

        private static void AddPrintRowsRecursive(List<PrintRow> rows, ReportLine line, int depth)
        {
            rows.Add(new PrintRow
            {
                Name = line.Name,
                Level = depth,
                AmountText = line.LineType == ReportLineType.MutedMetric
                    ? line.CurrentAmount.ToString("N2", CultureInfo.InvariantCulture) + "%"
                    : line.CurrentAmount.ToString("N2", CultureInfo.InvariantCulture),
                PercentText = line.PercentOfIncome.ToString("N2", CultureInfo.InvariantCulture) + "%",
                PreviousText = line.PreviousAmount.ToString("N2", CultureInfo.InvariantCulture),
                Bold = line.LineType == ReportLineType.SectionHeader || line.LineType == ReportLineType.Subtotal || line.LineType == ReportLineType.Highlight || line.LineType == ReportLineType.NetResult,
                ForeColor = line.LineType == ReportLineType.NetResult
                    ? (line.CurrentAmount >= 0m ? (Color?)Color.ForestGreen : Color.Firebrick)
                    : (Color?)null
            });

            if (line.Children == null)
            {
                return;
            }

            foreach (ReportLine child in line.Children)
            {
                AddPrintRowsRecursive(rows, child, depth + 1);
            }
        }

        private List<ExportRow> BuildExportRows()
        {
            List<ExportRow> rows = new List<ExportRow>();
            int rowIndex = 2;
            foreach (ReportLine line in _reportLines)
            {
                AddExportRowsRecursive(rows, line, 0, ref rowIndex);
            }

            foreach (ExportRow row in rows.Where(x => x.ChildRowIndexes.Count > 0))
            {
                int min = row.ChildRowIndexes.Min();
                int max = row.ChildRowIndexes.Max();
                row.AmountFormula = string.Format(CultureInfo.InvariantCulture, "=SUM(B{0}:B{1})", min, max);
                row.PreviousFormula = string.Format(CultureInfo.InvariantCulture, "=SUM(C{0}:C{1})", min, max);
            }

            return rows;
        }

        private static void AddExportRowsRecursive(List<ExportRow> rows, ReportLine line, int depth, ref int rowIndex)
        {
            ExportRow row = new ExportRow
            {
                RowIndex = rowIndex,
                Name = new string(' ', depth * 2) + line.Name,
                AmountValue = line.CurrentAmount,
                PreviousValue = line.PreviousAmount,
                PercentValue = line.PercentOfIncome,
                ChildRowIndexes = new List<int>()
            };

            rows.Add(row);
            rowIndex++;

            if (line.Children == null)
            {
                return;
            }

            foreach (ReportLine child in line.Children)
            {
                int before = rowIndex;
                AddExportRowsRecursive(rows, child, depth + 1, ref rowIndex);
                for (int idx = before; idx < rowIndex; idx++)
                {
                    row.ChildRowIndexes.Add(idx);
                }
            }
        }

        private static void WriteCsvWithFormulas(string filePath, List<ExportRow> rows)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("Line Item,Amount,Previous Period,Variance %,As % of Total Income");

            foreach (ExportRow row in rows)
            {
                string amountCell = string.IsNullOrWhiteSpace(row.AmountFormula)
                    ? row.AmountValue.ToString("N2", CultureInfo.InvariantCulture)
                    : row.AmountFormula;
                string previousCell = string.IsNullOrWhiteSpace(row.PreviousFormula)
                    ? row.PreviousValue.ToString("N2", CultureInfo.InvariantCulture)
                    : row.PreviousFormula;
                string varianceCell = string.Format(CultureInfo.InvariantCulture, "=IF(C{0}=0,0,(B{0}-C{0})/ABS(C{0}))", row.RowIndex);
                string percentCell = row.PercentValue.ToString("N2", CultureInfo.InvariantCulture) + "%";

                sb.Append(EscapeCsv(row.Name)).Append(',')
                    .Append(EscapeCsv(amountCell)).Append(',')
                    .Append(EscapeCsv(previousCell)).Append(',')
                    .Append(EscapeCsv(varianceCell)).Append(',')
                    .Append(EscapeCsv(percentCell)).AppendLine();
            }

            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
            Process.Start(filePath);
        }

        private static string EscapeCsv(string value)
        {
            string text = value ?? string.Empty;
            if (!text.Contains(",") && !text.Contains("\"") && !text.Contains("\n") && !text.Contains("\r"))
            {
                return text;
            }

            return "\"" + text.Replace("\"", "\"\"") + "\"";
        }

        private static bool OpenComposeWithAttachment(string attachmentPath)
        {
            MapiMessage message = new MapiMessage();
            MapiFileDesc file = new MapiFileDesc();
            file.nPosition = -1;
            file.lpszPathName = attachmentPath;
            file.lpszFileName = Path.GetFileName(attachmentPath);

            IntPtr filePtr = IntPtr.Zero;
            try
            {
                int fileSize = Marshal.SizeOf(typeof(MapiFileDesc));
                filePtr = Marshal.AllocHGlobal(fileSize);
                Marshal.StructureToPtr(file, filePtr, false);

                message.lpszSubject = "Income Statement (Profit & Loss)";
                message.lpszNoteText = "Please find the attached Profit & Loss report.";
                message.nFileCount = 1;
                message.lpFiles = filePtr;

                int result = MAPISendMail(IntPtr.Zero, IntPtr.Zero, message, MapiSendMailFlags.MAPI_DIALOG, 0);
                return result == 0 || result == 1;
            }
            finally
            {
                if (filePtr != IntPtr.Zero)
                {
                    Marshal.FreeHGlobal(filePtr);
                }
            }
        }

        [DllImport("MAPI32.DLL", CharSet = CharSet.Ansi)]
        private static extern int MAPISendMail(IntPtr sess, IntPtr hwnd, MapiMessage message, MapiSendMailFlags flags, int reserved);

        [Flags]
        private enum MapiSendMailFlags
        {
            MAPI_LOGON_UI = 0x00000001,
            MAPI_DIALOG = 0x00000008
        }

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
        private class MapiMessage
        {
            public int reserved;
            public string lpszSubject;
            public string lpszNoteText;
            public string lpszMessageType;
            public string lpszDateReceived;
            public string lpszConversationID;
            public int flFlags;
            public IntPtr lpOriginator;
            public int nRecipCount;
            public IntPtr lpRecips;
            public int nFileCount;
            public IntPtr lpFiles;
        }

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
        private struct MapiFileDesc
        {
            public int reserved;
            public int flFlags;
            public int nPosition;
            public string lpszPathName;
            public string lpszFileName;
            public IntPtr lpFileType;
        }

        private sealed class PrintRow
        {
            public string Name { get; set; }
            public int Level { get; set; }
            public string AmountText { get; set; }
            public string PercentText { get; set; }
            public string PreviousText { get; set; }
            public bool Bold { get; set; }
            public Color? ForeColor { get; set; }
        }

        private sealed class ExportRow
        {
            public int RowIndex { get; set; }
            public string Name { get; set; }
            public decimal AmountValue { get; set; }
            public decimal PreviousValue { get; set; }
            public decimal PercentValue { get; set; }
            public string AmountFormula { get; set; }
            public string PreviousFormula { get; set; }
            public List<int> ChildRowIndexes { get; set; }
        }

        private sealed class GroupInfo
        {
            public int Id { get; set; }
            public int ParentId { get; set; }
            public string Code { get; set; }
            public string Name { get; set; }
            public string Section { get; set; }
        }

        private sealed class AccountInfo
        {
            public int Id { get; set; }
            public int GroupId { get; set; }
            public string Code { get; set; }
            public string Name { get; set; }
            public string Section { get; set; }
            public decimal CurrentAmount { get; set; }
            public decimal PreviousAmount { get; set; }
        }

        private sealed class BalanceInfo
        {
            public decimal CurrentDebit { get; set; }
            public decimal CurrentCredit { get; set; }
            public decimal PreviousDebit { get; set; }
            public decimal PreviousCredit { get; set; }
        }

        private enum ReportLineType
        {
            SectionHeader,
            Group,
            Account,
            Subtotal,
            Highlight,
            MutedMetric,
            NetResult
        }

        private sealed class ReportLine
        {
            public string Name { get; set; }
            public int? AccountId { get; set; }
            public int Level { get; set; }
            public bool IsClickable { get; set; }
            public decimal CurrentAmount { get; set; }
            public decimal PreviousAmount { get; set; }
            public decimal PercentOfIncome { get; set; }
            public ReportLineType LineType { get; set; }
            public List<ReportLine> Children { get; set; }

            public static ReportLine SectionHeader(string name)
            {
                return new ReportLine { Name = name, LineType = ReportLineType.SectionHeader, Children = new List<ReportLine>() };
            }

            public static ReportLine Subtotal(string name, decimal amount)
            {
                return new ReportLine { Name = "= " + name, CurrentAmount = amount, LineType = ReportLineType.Subtotal, Children = new List<ReportLine>() };
            }

            public static ReportLine Highlight(string name, decimal amount)
            {
                return new ReportLine { Name = "= " + name, CurrentAmount = amount, LineType = ReportLineType.Highlight, Children = new List<ReportLine>() };
            }

            public static ReportLine MutedMetric(string name, decimal percent)
            {
                return new ReportLine { Name = "= " + name, CurrentAmount = percent, LineType = ReportLineType.MutedMetric, Children = new List<ReportLine>() };
            }

            public static ReportLine NetResult(string name, decimal amount)
            {
                return new ReportLine { Name = "= " + name, CurrentAmount = amount, LineType = ReportLineType.NetResult, Children = new List<ReportLine>() };
            }
        }
    }
}
