using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using POS.BLL;
using POS.Core;
using POS.DLL;
using pos.UI;
using pos.UI.Busy;

namespace pos
{
    public partial class frm_customer_payment : Form
    {
        private const string PaymentReferencePrefix = "[Payment Ref: ";

        private frm_addCustomer mainForm;
        private string _autoGeneratedDescription = string.Empty;
        public int _customer_id;
        public string _invoice_no;

        public int cash_account_id = 0;
        public int bank_account_id = 0;
        public int sales_account_id = 0;
        public int receivable_account_id = 0;
        public int sales_discount_acc_id = 0;
        private string _customer_name = string.Empty;

        // OPTIONAL: If you have a payable account id in company table, set it here.
        // If not available, keep 0 and supplier reference loading won't trigger.
        public int payable_account_id = 0;

        public frm_customer_payment(frm_addCustomer mainForm, int customer_id, string customer_name = "")
       {
            this.mainForm = mainForm;
            _customer_id = customer_id;
            _customer_name = customer_name;
            InitializeComponent();
            cmb_pendingInvoices.SelectedIndexChanged += cmb_pendingInvoices_SelectedIndexChanged;
            cmb_ref_account_code.SelectedIndexChanged += cmb_ref_account_code_SelectedIndexChanged;
        }

        public frm_customer_payment()
        {
            InitializeComponent();
            cmb_pendingInvoices.SelectedIndexChanged += cmb_pendingInvoices_SelectedIndexChanged;
            cmb_ref_account_code.SelectedIndexChanged += cmb_ref_account_code_SelectedIndexChanged;
           
        }
        
        public void frm_customer_payment_Load(object sender, EventArgs e)
        {
            try
            {
                using (BusyScope.Show(this, UiMessages.T("Loading...", "جاري التحميل...")))    {
                    Get_AccountID_From_Company();
                    get_accounts_dropdownlist();
                    GetMAXInvoiceNo();
                    LoadPendingInvoices();
                    lblCustomerName.Text = _customer_name;
                }
            }
            catch (Exception ex)
            {
                UiMessages.ShowError(ex.Message, ex.Message);
            }
        }

        public void get_accounts_dropdownlist()
        {
            GeneralBLL generalBLL_obj = new GeneralBLL();
            string keyword = "id,name";
            List<int> accountIds = new List<int>();

            if (cash_account_id > 0)
                accountIds.Add(cash_account_id);

            if (bank_account_id > 0 && !accountIds.Contains(bank_account_id))
                accountIds.Add(bank_account_id);

            DataTable accounts;
            if (accountIds.Count > 0)
            {
                string table = "acc_accounts where id IN (" + string.Join(",", accountIds.Distinct()) + ")";
                accounts = generalBLL_obj.GetRecord(keyword, table);
            }
            else
            {
                accounts = new DataTable();
                accounts.Columns.Add("id", typeof(int));
                accounts.Columns.Add("name", typeof(string));
            }

            DataRow emptyRow = accounts.NewRow();
            emptyRow[0] = 0;
            emptyRow[1] = "Please Select";
            accounts.Rows.InsertAt(emptyRow, 0);

            cmb_GL_account_code.DisplayMember = "name";
            cmb_GL_account_code.ValueMember = "id";
            cmb_GL_account_code.DataSource = accounts;

            if (cash_account_id > 0)
                cmb_GL_account_code.SelectedValue = cash_account_id;
            else if (bank_account_id > 0)
                cmb_GL_account_code.SelectedValue = bank_account_id;
            else
                cmb_GL_account_code.SelectedValue = 0;
        }

        public void GetMAXInvoiceNo()
        {
            JournalsBLL JournalsBLL_obj = new JournalsBLL();
            _invoice_no = JournalsBLL_obj.GetMaxInvoiceNo();
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(_invoice_no) || _customer_id == 0)
                {
                    UiMessages.ShowInfo(
                        "Please select a customer and enter the payment details.",
                        "يرجى اختيار عميل وإدخال بيانات الدفعة.",
                        "Validation",
                        "التحقق"
                    );
                    return;
                }

                if (string.IsNullOrWhiteSpace(txt_total_amount.Text))
                {
                    UiMessages.ShowInfo(
                        "Payment amount is required.",
                        "مبلغ الدفعة مطلوب.",
                        "Validation",
                        "التحقق"
                    );
                    return;
                }

                double amount;
                if (!double.TryParse(txt_total_amount.Text, out amount) || amount <= 0)
                {
                    UiMessages.ShowInfo(
                        "Please enter a valid payment amount.",
                        "يرجى إدخال مبلغ دفعة صحيح.",
                        "Validation",
                        "التحقق"
                    );
                    return;
                }

                double discountAmount = 0;
                if (!string.IsNullOrWhiteSpace(txt_discount.Text) && !double.TryParse(txt_discount.Text, out discountAmount))
                {
                    UiMessages.ShowInfo(
                        "Please enter a valid discount amount.",
                        "يرجى إدخال مبلغ خصم صحيح.",
                        "Validation",
                        "التحقق"
                    );
                    return;
                }

                string appliedInvoiceNo = GetAppliedInvoiceNo();
                double appliedInvoiceBalance = GetAppliedInvoiceBalance();
                if (!string.IsNullOrWhiteSpace(appliedInvoiceNo) && (amount + discountAmount) > appliedInvoiceBalance + 0.0001)
                {
                    UiMessages.ShowWarning(
                        "Payment plus discount cannot be greater than the selected invoice balance.",
                        "لا يمكن أن يكون مبلغ الدفعة مع الخصم أكبر من رصيد الفاتورة المحددة.",
                        "Validation",
                        "التحقق"
                    );
                    return;
                }

                var confirm = UiMessages.ConfirmYesNo(
                    "Post this customer payment?",
                    "هل تريد ترحيل دفعة العميل؟",
                    captionEn: "Confirm",
                    captionAr: "تأكيد"
                );

                if (confirm != DialogResult.Yes)
                    return;

                // CHECK PERIOD LOCK BEFORE POSTING
                DateTime paymentDate = txt_payment_date.Value.Date;
                FinancialPeriodBLL periodBll = new FinancialPeriodBLL();
                if (periodBll.IsPeriodLocked(paymentDate))
                {
                    UiMessages.ShowError(
                        periodBll.GetPeriodLockReason(paymentDate),
                        "The financial period for this date is closed or locked. No new transactions are allowed.",
                        "Period Locked",
                        "الفترة مقفلة"
                    );
                    return;
                }

                using (BusyScope.Show(this, UiMessages.T("Posting payment...", "جاري ترحيل الدفعة...")))
                {
                    int GL_account_id = (cmb_GL_account_code.SelectedValue == null ? 0 : int.Parse(cmb_GL_account_code.SelectedValue.ToString()));
                    int Ref_account_id = (cmb_ref_account_code.SelectedValue == null ? 0 : int.Parse(cmb_ref_account_code.SelectedValue.ToString()));

                    if (GL_account_id <= 0)
                    {
                        UiMessages.ShowInfo(
                            "Please select a valid cash or bank account.",
                            "يرجى اختيار حساب نقدي أو بنكي صحيح.",
                            "Validation",
                            "التحقق"
                        );
                        return;
                    }

                    if (receivable_account_id <= 0)
                    {
                        UiMessages.ShowInfo(
                            "Default accounts receivable is not configured. Please configure it in Accounting Settings.",
                            "حساب الذمم المدينة الافتراضي غير مهيأ. يرجى ضبطه من إعدادات المحاسبة.",
                            "Validation",
                            "التحقق"
                        );
                        return;
                    }

                    bool isBankPayment = IsBankPaymentAccount(GL_account_id);
                    if (isBankPayment && Ref_account_id <= 0)
                    {
                        UiMessages.ShowInfo(
                            "Please select a bank account reference.",
                            "يرجى اختيار مرجع الحساب البنكي.",
                            "Validation",
                            "التحقق"
                        );
                        return;
                    }

                    string bankName = isBankPayment ? GetSelectedReferenceDisplayText() : string.Empty;
                    int? bankId = isBankPayment ? (int?)Ref_account_id : null;

                    string userRemarks = GetEffectiveRemarks();
                    string ledgerInvoiceNo = string.IsNullOrWhiteSpace(appliedInvoiceNo) ? _invoice_no : appliedInvoiceNo;
                    string journalDescription = BuildPaymentDescription(appliedInvoiceNo, userRemarks, isBankPayment, bankName, false, _invoice_no, false, _customer_name);
                    string ledgerDescription = BuildPaymentDescription(appliedInvoiceNo, userRemarks, isBankPayment, bankName, true, _invoice_no, false, _customer_name);
                    string discountJournalDescription = BuildPaymentDescription(appliedInvoiceNo, userRemarks, isBankPayment, bankName, false, _invoice_no, true, _customer_name);
                    string discountLedgerDescription = BuildPaymentDescription(appliedInvoiceNo, userRemarks, isBankPayment, bankName, true, _invoice_no, true, _customer_name);

                    List<JVLineModel> lines = new List<JVLineModel>();
                    lines.Add(new JVLineModel
                    {
                        AccountId = GL_account_id,
                        Debit = Convert.ToDecimal(amount),
                        Credit = 0m,
                        Narration = journalDescription,
                        ModuleName = "CUSTOMER_PAYMENT",
                        BankId = bankId
                    });

                    lines.Add(new JVLineModel
                    {
                        AccountId = receivable_account_id,
                        Debit = 0m,
                        Credit = Convert.ToDecimal(amount),
                        Narration = ledgerDescription,
                        ModuleName = "CUSTOMER_PAYMENT",
                        CustomerId = _customer_id
                    });

                    if (discountAmount > 0)
                    {
                        if (sales_discount_acc_id <= 0)
                        {
                            UiMessages.ShowInfo(
                                "Default discount account is not configured. Please configure it in Accounting Settings.",
                                "حساب الخصم الافتراضي غير مهيأ. يرجى ضبطه من إعدادات المحاسبة.",
                                "Validation",
                                "التحقق"
                            );
                            return;
                        }

                        lines.Add(new JVLineModel
                        {
                            AccountId = sales_discount_acc_id,
                            Debit = Convert.ToDecimal(discountAmount),
                            Credit = 0m,
                            Narration = discountJournalDescription,
                            ModuleName = "CUSTOMER_PAYMENT"
                        });

                        lines.Add(new JVLineModel
                        {
                            AccountId = receivable_account_id,
                            Debit = 0m,
                            Credit = Convert.ToDecimal(discountAmount),
                            Narration = discountLedgerDescription,
                            ModuleName = "CUSTOMER_PAYMENT",
                            CustomerId = _customer_id
                        });
                    }

                    AutoJVModel model = new AutoJVModel
                    {
                        ModuleName = "RECEIPT",
                        RefModule = "pos_customers_payments",
                        RefId = _customer_id,
                        VoucherDate = txt_payment_date.Value.Date,
                        ReferenceNo = ledgerInvoiceNo,
                        Narration = journalDescription,
                        IsAutoPosted = true,
                        BranchId = UsersModal.logged_in_branch_id,
                        Lines = lines
                    };

                    JournalsBLL journalsBll = new JournalsBLL();
                    PostResult postResult = journalsBll.PostAutoJournalEntry(model, UsersModal.logged_in_userid);

                    if (postResult != null && postResult.Success)
                    {
                        Log.LogAction(
                            "Post Customer Payment",
                            "CustomerId=" + _customer_id
                            + " | PaymentRef=" + _invoice_no
                            + " | VoucherNo=" + postResult.VoucherNo
                            + " | AppliedInvoice=" + (string.IsNullOrWhiteSpace(appliedInvoiceNo) ? "(none)" : appliedInvoiceNo)
                            + " | Amount=" + amount.ToString("N2")
                            + " | Discount=" + discountAmount.ToString("N2")
                            + " | GLAccountId=" + GL_account_id
                            + " | RefAccountId=" + Ref_account_id,
                            UsersModal.logged_in_userid,
                            UsersModal.logged_in_branch_id);

                        UiMessages.ShowInfo(
                            string.IsNullOrWhiteSpace(appliedInvoiceNo) ? "Payment has been posted successfully." : "Payment has been posted successfully against invoice " + appliedInvoiceNo + ".",
                            string.IsNullOrWhiteSpace(appliedInvoiceNo) ? "تم ترحيل الدفعة بنجاح." : "تم ترحيل الدفعة بنجاح مقابل الفاتورة " + appliedInvoiceNo + ".",
                            "Success",
                            "نجاح"
                        );
                    }
                    else
                    {
                        string errorMessage = "Payment could not be posted. Please try again.";
                        if (postResult != null && postResult.Messages != null && postResult.Messages.Count > 0)
                        {
                            ValidationError firstError = postResult.Messages.FirstOrDefault(x => x.IsBlocking) ?? postResult.Messages.FirstOrDefault();
                            if (firstError != null && !string.IsNullOrWhiteSpace(firstError.Message))
                                errorMessage = firstError.Message;
                        }

                        UiMessages.ShowError(
                            errorMessage,
                            errorMessage,
                            "Error",
                            "خطأ"
                        );
                        return;
                    }

                    if (mainForm != null)
                        mainForm.load_customer_transactions_grid(_customer_id);

                    this.Close();
                }
            }
            catch (Exception ex)
            {
                UiMessages.ShowError(ex.Message, ex.Message);
            }
        }
        
        private int Insert_Journal_entry(string invoice_no, int account_id, double debit, double credit, DateTime date,
           string description, int customer_id, int supplier_id, int entry_id,int bank_id,string payment_ref_invoice_no = "")
        {
            int journal_id = 0;
            JournalsModal JournalsModal_obj = new JournalsModal();
            JournalsBLL JournalsObj = new JournalsBLL();

            JournalsModal_obj.invoice_no = invoice_no;
            JournalsModal_obj.entry_date = date;
            JournalsModal_obj.debit = debit;
            JournalsModal_obj.credit = credit;
            JournalsModal_obj.account_id = account_id;
            JournalsModal_obj.description = description;
            JournalsModal_obj.customer_id = customer_id;
            JournalsModal_obj.supplier_id = supplier_id;
            JournalsModal_obj.bank_id = bank_id;
            JournalsModal_obj.entry_id = entry_id;
            JournalsModal_obj.payment_ref_invoice_no = payment_ref_invoice_no;

            journal_id = JournalsObj.Insert(JournalsModal_obj);
            return journal_id;
        }

        private void Get_AccountID_From_Company()
        {
            cash_account_id = ResolveDefaultAccountId(SettingKeys.DefaultCashAccount);
            bank_account_id = ResolveDefaultAccountId(SettingKeys.DefaultBankAccount);
            receivable_account_id = ResolveDefaultAccountId(SettingKeys.DefaultArAccount);
            sales_discount_acc_id = ResolveDefaultAccountId(SettingKeys.DefaultDiscountAccount);
            sales_account_id = ResolveDefaultAccountId(SettingKeys.DefaultSalesAccount);
            payable_account_id = ResolveDefaultAccountId(SettingKeys.DefaultApAccount);
        }

        private int ResolveDefaultAccountId(string settingKey)
        {
            if (string.IsNullOrWhiteSpace(settingKey))
                return 0;

            try
            {
                GeneralBLL objBLL = new GeneralBLL();
                string safeKey = settingKey.Replace("'", "''");
                DataTable settingDt = objBLL.GetRecord("TOP 1 setting_value", "pos_settings WHERE setting_key='" + safeKey + "'");
                if (settingDt == null || settingDt.Rows.Count == 0 || settingDt.Rows[0]["setting_value"] == DBNull.Value)
                    return 0;

                string accountCode = Convert.ToString(settingDt.Rows[0]["setting_value"]);
                if (string.IsNullOrWhiteSpace(accountCode))
                    return 0;

                string safeCode = accountCode.Trim().Replace("'", "''");
                DataTable accountDt = objBLL.GetRecord("TOP 1 id", "acc_accounts WHERE LTRIM(RTRIM(code))='" + safeCode + "'");
                if (accountDt == null || accountDt.Rows.Count == 0 || accountDt.Rows[0]["id"] == DBNull.Value)
                    return 0;

                int accountId;
                return int.TryParse(Convert.ToString(accountDt.Rows[0]["id"]), out accountId) ? accountId : 0;
            }
            catch
            {
                return 0;
            }
        }

        private bool IsBankPaymentAccount(int glAccountId)
        {
            if (glAccountId <= 0)
                return false;

            if (bank_account_id > 0 && glAccountId == bank_account_id)
                return true;

            try
            {
                GeneralBLL objBLL = new GeneralBLL();
                DataTable bankDt = objBLL.GetRecord("TOP 1 id", "pos_banks WHERE GLAccountID=" + glAccountId);
                if (bankDt != null && bankDt.Rows.Count > 0)
                    return true;
            }
            catch
            {
            }

            return new BankBLL().IsBankGlAccount(glAccountId);
        }

        private void btn_cancel_Click(object sender, EventArgs e)
        {
            this.Dispose(); 
            this.Close();
        }

        private void frm_customer_payment_KeyDown(object sender, KeyEventArgs e)
        {
            //when you enter in textbox it will goto next textbox, work like TAB key
            if (e.KeyData == Keys.Enter)
            {
                SendKeys.Send("{TAB}");
            }
        }


        private void txt_total_amount_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!char.IsControl(e.KeyChar) && !char.IsDigit(e.KeyChar) && (e.KeyChar != '.'))
            {
                e.Handled = true;
            }

            // only allow one decimal point
            if ((e.KeyChar == '.') && ((sender as TextBox).Text.IndexOf('.') > -1))
            {
                e.Handled = true;
            }
        }

        private void txt_discount_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!char.IsControl(e.KeyChar) && !char.IsDigit(e.KeyChar) && (e.KeyChar != '.'))
            {
                e.Handled = true;
            }

            // only allow one decimal point
            if ((e.KeyChar == '.') && ((sender as TextBox).Text.IndexOf('.') > -1))
            {
                e.Handled = true;
            }
        }

        private void cmb_cash_account_code_SelectedIndexChanged(object sender, EventArgs e)
        {
            // Implement "reference account" loading based on selected GL account:
            // - Receivable GL -> Customers list
            // - Payable GL -> Suppliers list (if available)
            // - Bank GL -> Bank accounts for that GL account
            // - Otherwise -> clear ref combo

            int glAccountId = 0;
            try
            {
                glAccountId = (cmb_GL_account_code.SelectedValue == null)
                    ? 0
                    : Convert.ToInt32(cmb_GL_account_code.SelectedValue);
            }
            catch
            {
                glAccountId = 0;
            }

            if (glAccountId <= 0)
            {
                ClearRefCombo();
                return;
            }

            if (glAccountId == receivable_account_id)
            {
                LoadCustomersIntoRefCombo();
                UpdateSuggestedDescription();
                return;
            }

            if (glAccountId == payable_account_id)
            {
                LoadSuppliersIntoRefCombo();
                UpdateSuggestedDescription();
                return;
            }
            if (IsBankPaymentAccount(glAccountId))
            {
                LoadBankAccountsIntoRefCombo(glAccountId);
                UpdateSuggestedDescription();
                return;
            }

            ClearRefCombo();
            UpdateSuggestedDescription();
        }

        private void LoadCustomersIntoRefCombo()
        {
            // Expected table: `pos_customers` with columns: id, first_name, last_name (or name).
            // We build a simple display name using common columns, falling back to "id".
            try
            {
                GeneralBLL bll = new GeneralBLL();

                // Be pragmatic: request a set of columns that commonly exist.
                // If some columns don't exist, DB will error; we catch and fallback.
                DataTable dt;

                try
                {
                    dt = bll.GetRecord("TOP 500 id, first_name, last_name", "pos_customers");
                    if (!dt.Columns.Contains("display_name"))
                        dt.Columns.Add("display_name", typeof(string));

                    foreach (DataRow row in dt.Rows)
                    {
                        var fn = dt.Columns.Contains("first_name") && row["first_name"] != DBNull.Value ? row["first_name"].ToString() : "";
                        var ln = dt.Columns.Contains("last_name") && row["last_name"] != DBNull.Value ? row["last_name"].ToString() : "";
                        var name = (fn + " " + ln).Trim();
                        if (string.IsNullOrWhiteSpace(name))
                            name = "Customer #" + row["id"].ToString();

                        row["display_name"] = name;
                    }

                    BindCombo(cmb_ref_account_code, dt, "id", "display_name","customer");
                    return;
                }
                catch
                {
                    // Fallback: try a generic `name` column
                }

                dt = bll.GetRecord("TOP 500 id, name", "pos_customers");
                BindCombo(cmb_ref_account_code, dt, "id", "name","Customer");
            }
            catch
            {
                ClearRefCombo();
            }
        }

        private void LoadSuppliersIntoRefCombo()
        {
            // Expected table: `pos_suppliers` with columns: id, name (common).
            try
            {
                GeneralBLL bll = new GeneralBLL();
                DataTable dt = bll.GetRecord("TOP 500 id, CONCAT(first_name,' ',last_name) as name", "pos_suppliers");
                BindCombo(cmb_ref_account_code, dt, "id", "name","Supplier");
            }
            catch
            {
                ClearRefCombo();
            }
        }

        private void LoadBankAccountsIntoRefCombo(int glAccountId)
        {
            // Expected table: `pos_bank_accounts` with columns: id, account_title (or name), gl_account_id.
            // The project's `GeneralBLL.GetRecord` API doesn't support WHERE in provided usage,
            // so we request a subset of columns and then filter in-memory.
            try
            {
                GeneralBLL bll = new GeneralBLL();

                DataTable dt;
                try
                {
                    dt = bll.GetRecord("TOP 500 id, name, GLAccountID", "pos_banks");
                    DataView dv = dt.DefaultView;
                    dv.RowFilter = "GLAccountID = " + glAccountId;
                    BindCombo(cmb_ref_account_code, dv.ToTable(), "id", "name");
                    return;
                }
                catch
                {
                    // Fallback to `name`
                }

                dt = bll.GetRecord("TOP 500 id, name, GLAccountID", "pos_banks");
                DataView dv2 = dt.DefaultView;
                dv2.RowFilter = "GLAccountID = " + glAccountId;
                BindCombo(cmb_ref_account_code, dv2.ToTable(), "id", "name","Bank");
            }
            catch
            {
                ClearRefCombo();
            }
        }

        
        private bool IsReceivableAccount(int glAccountId)
        {
            try
            {
                GeneralBLL bll = new GeneralBLL();
                DataTable dt = bll.GetRecord("TOP 500 id, name", "acc_accounts");

                foreach (DataRow row in dt.Rows)
                {
                    if (row["id"] == DBNull.Value) continue;
                    if (Convert.ToInt32(row["id"]) != glAccountId) continue;

                    if (!dt.Columns.Contains("name") || row["name"] == DBNull.Value)
                        return false;

                    var t = row["name"].ToString().Trim();

                    // String-based detection
                    if (t.Equals("Account Receivable", StringComparison.OrdinalIgnoreCase))
                        return true;

                    // Numeric-based detection (if your DB uses codes)
                    int code;
                    if (int.TryParse(t, out code))
                    {
                        // Adjust this if your system has a known Account Receivable code.
                        // Keep conservative: assume code 5 indicates Account Receivable (common pattern in some POS schemas).
                        if (code == 5) return true;
                    }

                    return false;
                }

                return false;
            }
            catch
            {
                return false;
            }
        }
        private bool IsPayableAccount(int glAccountId)
        {
            try
            {
                GeneralBLL bll = new GeneralBLL();
                DataTable dt = bll.GetRecord("TOP 500 id, name", "acc_accounts");
                foreach (DataRow row in dt.Rows)
                {
                    if (row["id"] == DBNull.Value) continue;
                    if (Convert.ToInt32(row["id"]) != glAccountId) continue;
                    if (!dt.Columns.Contains("name") || row["name"] == DBNull.Value)
                        return false;
                    var t = row["name"].ToString().Trim();
                    // String-based detection
                    if (t.Equals("Account Payable", StringComparison.OrdinalIgnoreCase))
                        return true;
                    // Numeric-based detection (if your DB uses codes)
                    int code;
                    if (int.TryParse(t, out code))
                    {
                        // Adjust this if your system has a known Account Payable code.
                        // Keep conservative: assume code 6 indicates Account Payable (common pattern in some POS schemas).
                        if (code == 6) return true;
                    }
                    return false;
                }
                return false;
            }
            catch
            {
                return false;
            }
        }
        private void BindCombo(ComboBox combo, DataTable dt, string valueMember, string displayMember, string type = "Account")
        {
            if (combo == null) return;

            combo.DataSource = null;

            //DataRow emptyRow = dt.NewRow();
            //emptyRow[0] = 0;              // Set Column Value
            //emptyRow[1] = "Please Select "+ type;              // Set Column Value
            //dt.Rows.InsertAt(emptyRow, 0);

            combo.DisplayMember = displayMember;
            combo.ValueMember = valueMember;
            combo.DataSource = dt;

            combo.Enabled = (dt != null && dt.Rows.Count > 0);
            if (combo.Enabled)
                combo.SelectedIndex = 0;
        }

        private void ClearRefCombo()
        {
            if (cmb_ref_account_code == null) return;
            cmb_ref_account_code.DataSource = null;
            cmb_ref_account_code.Items.Clear();
            cmb_ref_account_code.Text = string.Empty;
            cmb_ref_account_code.Enabled = false;
        }

        private void LoadPendingInvoices()
        {
            if (cmb_pendingInvoices == null)
                return;

            cmb_pendingInvoices.DataSource = null;
            cmb_pendingInvoices.Items.Clear();

            if (_customer_id <= 0)
            {
                cmb_pendingInvoices.Enabled = false;
                return;
            }

            CustomerBLL customerBLL = new CustomerBLL();
            DataTable dt = customerBLL.GetPendingCustomerInvoices(_customer_id);

            if (!dt.Columns.Contains("invoice_no"))
                dt.Columns.Add("invoice_no", typeof(string));
            if (!dt.Columns.Contains("display_text"))
                dt.Columns.Add("display_text", typeof(string));
            if (!dt.Columns.Contains("balance_amount"))
                dt.Columns.Add("balance_amount", typeof(decimal));

            DataRow emptyRow = dt.NewRow();
            emptyRow["invoice_no"] = string.Empty;
            emptyRow["display_text"] = "-- Select Invoice --";
            emptyRow["balance_amount"] = 0m;
            dt.Rows.InsertAt(emptyRow, 0);

            cmb_pendingInvoices.DisplayMember = "display_text";
            cmb_pendingInvoices.ValueMember = "invoice_no";
            cmb_pendingInvoices.DataSource = dt;
            cmb_pendingInvoices.SelectedIndex = 0;
            cmb_pendingInvoices.Enabled = dt.Rows.Count > 1;
        }

        private void cmb_pendingInvoices_SelectedIndexChanged(object sender, EventArgs e)
        {
            string appliedInvoiceNo = GetAppliedInvoiceNo();
            double balance = GetAppliedInvoiceBalance();

            if (!string.IsNullOrWhiteSpace(appliedInvoiceNo))
            {
                double existingAmount;
                if (string.IsNullOrWhiteSpace(txt_total_amount.Text) || !double.TryParse(txt_total_amount.Text, out existingAmount) || existingAmount <= 0)
                    txt_total_amount.Text = Math.Round(balance, 2).ToString("N2");
            }

            UpdateSuggestedDescription();
        }

        private void cmb_ref_account_code_SelectedIndexChanged(object sender, EventArgs e)
        {
            UpdateSuggestedDescription();
        }

        private string GetAppliedInvoiceNo()
        {
            return cmb_pendingInvoices == null || cmb_pendingInvoices.SelectedValue == null
                ? string.Empty
                : Convert.ToString(cmb_pendingInvoices.SelectedValue);
        }

        private double GetAppliedInvoiceBalance()
        {
            if (cmb_pendingInvoices == null || cmb_pendingInvoices.SelectedItem == null)
                return 0;

            DataRowView rowView = cmb_pendingInvoices.SelectedItem as DataRowView;
            if (rowView == null || rowView.Row == null || !rowView.Row.Table.Columns.Contains("balance_amount"))
                return 0;

            double balance;
            return double.TryParse(Convert.ToString(rowView["balance_amount"]), out balance) ? balance : 0;
        }

        private static string BuildLedgerDescription(string paymentReferenceInvoiceNo, string appliedInvoiceNo, string description)
        {
            string baseDescription = (description ?? string.Empty).Trim();
            string againstInvoice = string.IsNullOrWhiteSpace(appliedInvoiceNo) ? string.Empty : "Against Invoice: " + appliedInvoiceNo;
            string paymentReference = PaymentReferencePrefix + paymentReferenceInvoiceNo + "]";

            if (string.IsNullOrWhiteSpace(baseDescription))
                return string.IsNullOrWhiteSpace(againstInvoice) ? paymentReference : againstInvoice + " " + paymentReference;

            if (string.IsNullOrWhiteSpace(againstInvoice))
                return baseDescription + " " + paymentReference;

            return againstInvoice + " | " + baseDescription + " " + paymentReference;
        }

        private void UpdateSuggestedDescription()
        {
            if (txt_description == null)
                return;

            string suggested = BuildPaymentDescription(
                GetAppliedInvoiceNo(),
                string.Empty,
                IsSelectedBankPayment(),
                GetSelectedReferenceDisplayText(),
                false,
                _invoice_no,
                false,
                _customer_name);

            string currentText = (txt_description.Text ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(currentText) || string.Equals(currentText, _autoGeneratedDescription, StringComparison.OrdinalIgnoreCase))
                txt_description.Text = suggested;

            _autoGeneratedDescription = suggested;
        }

        private string GetSelectedReferenceDisplayText()
        {
            if (cmb_ref_account_code == null)
                return string.Empty;

            DataRowView rowView = cmb_ref_account_code.SelectedItem as DataRowView;
            if (rowView != null)
            {
                if (rowView.Row.Table.Columns.Contains("display_name"))
                    return Convert.ToString(rowView["display_name"]);

                if (rowView.Row.Table.Columns.Contains("name"))
                    return Convert.ToString(rowView["name"]);
            }

            return Convert.ToString(cmb_ref_account_code.Text);
        }

        private string GetSelectedGlAccountDisplayText()
        {
            return cmb_GL_account_code == null ? string.Empty : Convert.ToString(cmb_GL_account_code.Text);
        }

        private bool IsSelectedBankPayment()
        {
            int glAccountId;
            if (cmb_GL_account_code == null || cmb_GL_account_code.SelectedValue == null || !int.TryParse(Convert.ToString(cmb_GL_account_code.SelectedValue), out glAccountId))
                return false;

            return IsBankPaymentAccount(glAccountId);
        }

        private string GetEffectiveRemarks()
        {
            string currentText = (txt_description.Text ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(currentText))
                return string.Empty;

            return string.Equals(currentText, _autoGeneratedDescription, StringComparison.OrdinalIgnoreCase)
                ? string.Empty
                : currentText;
        }

        private string BuildPaymentDescription(string appliedInvoiceNo, string remarks, bool isBankPayment, string bankName, bool includePaymentReference, string paymentReferenceInvoiceNo, bool isDiscount, string customerName)
        {
            bool isArabic = IsArabicEnvironment();

            string customerPart = string.IsNullOrWhiteSpace(customerName)
                ? string.Empty
                : (isArabic ? " للعميل " + customerName.Trim() : " for customer " + customerName.Trim());
 
            string invoicePart = string.IsNullOrWhiteSpace(appliedInvoiceNo)
                ? (isArabic ? "على حساب العميل" : "on customer account")
                : (isArabic ? "مقابل الفاتورة " + appliedInvoiceNo : "against invoice " + appliedInvoiceNo);

            string paymentMode = isBankPayment
                ? (string.IsNullOrWhiteSpace(bankName)
                    ? (isArabic ? "البنك" : "Bank")
                    : (isArabic ? "البنك: " + bankName : "Bank: " + bankName))
                : GetSelectedGlAccountDisplayText();

            if (string.IsNullOrWhiteSpace(paymentMode))
                paymentMode = isBankPayment
                    ? (isArabic ? "البنك" : "Bank")
                    : (isArabic ? "النقد" : "Cash");

            string description = isDiscount
                ? (isArabic
                    ? "تم ترحيل خصم دفعة العميل" + customerPart + " " + invoicePart + " عبر " + paymentMode + "."
                    : "Customer payment discount posted" + customerPart + " " + invoicePart + " via " + paymentMode + ".")
                : (isArabic
                    ? "تم استلام دفعة العميل" + customerPart + " " + invoicePart + " عبر " + paymentMode + "."
                    : "Customer payment received" + customerPart + " " + invoicePart + " via " + paymentMode + ".");
            
            if (!string.IsNullOrWhiteSpace(remarks))
                description += isArabic
                    ? " ملاحظات: " + remarks.Trim() + "."
                    : " Remarks: " + remarks.Trim() + ".";

            if (includePaymentReference && !string.IsNullOrWhiteSpace(paymentReferenceInvoiceNo))
                description += " " + PaymentReferencePrefix + paymentReferenceInvoiceNo + "]";

            return description.Trim();
        }

        private static bool IsArabicEnvironment()
        {
            string lang = UsersModal.logged_in_lang ?? string.Empty;
            return lang.StartsWith("ar", StringComparison.OrdinalIgnoreCase);
        }
    }
}
